# Generated by Django 3.2.6 on 2021-08-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cclass', models.CharField(max_length=30)),
                ('pw', models.CharField(max_length=64)),
                ('alignment', models.CharField(choices=[('g', 'Good'), ('n', 'Neutral'), ('e', 'Evil')], default='n', max_length=1)),
                ('isadmin', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('nick', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
                ('nextlvl', models.IntegerField()),
                ('userhost', models.CharField(max_length=255)),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('idled', models.IntegerField()),
                ('penmessage', models.IntegerField()),
                ('pennick', models.IntegerField()),
                ('penpart', models.IntegerField()),
                ('penkick', models.IntegerField()),
                ('penquit', models.IntegerField()),
                ('pendropped', models.IntegerField()),
                ('penquest', models.IntegerField()),
                ('penlogout', models.IntegerField()),
                ('created', models.DateTimeField(editable=False)),
                ('lastlogin', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dawdle.player')),
            ],
        ),
    ]
