# Generated by Django 3.2.6 on 2021-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawdle', '0002_auto_20210828_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastlogin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
