# Generated by Django 3.2.6 on 2021-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawdle', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(default=0)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
                ('p4', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=400)),
                ('qtime', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('dest1x', models.IntegerField(default=0)),
                ('dest1y', models.IntegerField(default=0)),
                ('dest2x', models.IntegerField(default=0)),
                ('dest2y', models.IntegerField(default=0)),
            ],
        ),
    ]
