# Generated by Django 3.2.6 on 2021-10-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawdle', '0007_item_unique_item_owner_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('baseclass', models.CharField(max_length=30)),
                ('fullclass', models.CharField(max_length=30)),
                ('alignment', models.CharField(choices=[('g', 'Good'), ('n', 'Neutral'), ('e', 'Evil')], default='n', max_length=1)),
                ('level', models.IntegerField(default=0)),
                ('nextlvl', models.IntegerField(default=600)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dawdle.player')),
            ],
        ),
    ]
