# Generated by Django 3.2.6 on 2021-09-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawdleweb', '0003_auto_20210828_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(default='helm', max_length=10),
            preserve_default=False,
        ),
    ]
